spring:
    main:
        allow-bean-definition-overriding: true
    thymeleaf:
        cache: false
        prefix: classpath:/templates
server:
    ssl:
        key-store: classpath:springboot.p12
        key-store-password: password
        key-store-type: pkcs12
        key-alias: springboot
        key-password: password
    port: 8443